"use server";

import nodemailer from "nodemailer";
import { z } from "zod";

const ContactSchema = z.object({
  name: z.string().min(1, "Name is required"),
  email: z.string().email("Invalid email address"),
  message: z.string().min(1, "Message is required"),
});

export async function submitContactForm({ data }: { data: { name: string; email: string; message: string } }) {
  const result = ContactSchema.safeParse(data);
  if (!result.success) {
    throw new Error(result.error.errors[0].message);
  }

  const { name, email, message } = result.data;

  if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
    throw new Error("SMTP credentials not configured.");
  }

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  const html = `
    <div style="font-family: 'Helvetica Neue', Arial, sans-serif; background-color: #FBF9F6; padding: 40px 20px; color: #333;">
      <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.05);">
        
        <!-- Header -->
        <div style="background-color: #722F37; padding: 30px; text-align: center;">
          <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 600; letter-spacing: 1px;">New Contact Request</h1>
        </div>
        
        <!-- Body -->
        <div style="padding: 40px 30px;">
          <p style="font-size: 16px; line-height: 1.5; margin-bottom: 25px;">You have received a new message from the <strong>FizTopz</strong> contact form.</p>
          
          <div style="background-color: #f9f9f9; border-left: 4px solid #722F37; padding: 20px; margin-bottom: 30px; border-radius: 0 4px 4px 0;">
            <h3 style="margin-top: 0; margin-bottom: 15px; font-size: 14px; color: #666; text-transform: uppercase; letter-spacing: 1px;">Customer Details</h3>
            <p style="margin: 0 0 10px 0;"><strong>Name:</strong> ${name}</p>
            <p style="margin: 0;"><strong>Email:</strong> <a href="mailto:${email}" style="color: #722F37; text-decoration: none;">${email}</a></p>
          </div>
          
          <h3 style="margin-top: 0; margin-bottom: 15px; font-size: 14px; color: #666; text-transform: uppercase; letter-spacing: 1px;">Message</h3>
          <div style="background-color: #ffffff; border: 1px solid #e0e0e0; padding: 20px; border-radius: 4px; font-size: 15px; line-height: 1.6; white-space: pre-wrap; color: #444;">${message}</div>
          
          <!-- Action -->
          <div style="text-align: center; margin-top: 40px;">
            <a href="mailto:${email}?subject=Re: Your Contact Request to FizTopz" style="display: inline-block; background-color: #722F37; color: #ffffff; text-decoration: none; padding: 14px 30px; font-size: 16px; font-weight: bold; border-radius: 4px; letter-spacing: 1px;">REPLY TO CUSTOMER</a>
          </div>
        </div>
        
        <!-- Footer -->
        <div style="background-color: #f4f4f4; padding: 20px; text-align: center; font-size: 12px; color: #888;">
          <p style="margin: 0;">This email was automatically generated by your FizTopz storefront.</p>
        </div>
        
      </div>
    </div>
  `;

  try {
    await transporter.sendMail({
      from: `"${name}" <${process.env.SMTP_USER}>`,
      to: "fiztopzfeb@gmail.com",
      replyTo: email,
      subject: `New Contact Message from ${name}`,
      html,
    });
    return { success: true };
  } catch (err: any) {
    console.error("Nodemailer error:", err);
    throw new Error("Failed to send message. Please try again later.");
  }
}
